In [52]:
import pandas as pd

df = pd.read_csv("iris.csv")

df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [53]:
import numpy as np 

df['x'] = df[df.columns[:4]].values.tolist()
df['x']

0      [5.1, 3.5, 1.4, 0.2]
1      [4.9, 3.0, 1.4, 0.2]
2      [4.7, 3.2, 1.3, 0.2]
3      [4.6, 3.1, 1.5, 0.2]
4      [5.0, 3.6, 1.4, 0.2]
               ...         
145    [6.7, 3.0, 5.2, 2.3]
146    [6.3, 2.5, 5.0, 1.9]
147    [6.5, 3.0, 5.2, 2.0]
148    [6.2, 3.4, 5.4, 2.3]
149    [5.9, 3.0, 5.1, 1.8]
Name: x, Length: 150, dtype: object

In [54]:
import numpy as np

np.unique(df['variety'])

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [55]:
df['class'] = df['variety'].replace({"Setosa":0, "Versicolor":1, "Virginica":2})

/tmp/ipykernel_3720/55725183.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['class'] = df['variety'].replace({"Setosa":0, "Versicolor":1, "Virginica":2})


In [56]:
df['y'] = df['class'].apply(lambda x: x+1)
df['y']

0      1
1      1
2      1
3      1
4      1
      ..
145    3
146    3
147    3
148    3
149    3
Name: y, Length: 150, dtype: int64

In [57]:
df.describe()

sepal.length  sepal.width  petal.length  petal.width       class  \
count    150.000000   150.000000    150.000000   150.000000  150.000000   
mean       5.843333     3.057333      3.758000     1.199333    1.000000   
std        0.828066     0.435866      1.765298     0.762238    0.819232   
min        4.300000     2.000000      1.000000     0.100000    0.000000   
25%        5.100000     2.800000      1.600000     0.300000    0.000000   
50%        5.800000     3.000000      4.350000     1.300000    1.000000   
75%        6.400000     3.300000      5.100000     1.800000    2.000000   
max        7.900000     4.400000      6.900000     2.500000    2.000000   

                y  
count  150.000000  
mean     2.000000  
std      0.819232  
min      1.000000  
25%      1.000000  
50%      2.000000  
75%      3.000000  
max      3.000000

In [58]:
df.to_csv("iris_ok.csv", index=False)

In [59]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [60]:
df['x']

0      [5.1, 3.5, 1.4, 0.2]
1      [4.9, 3.0, 1.4, 0.2]
2      [4.7, 3.2, 1.3, 0.2]
3      [4.6, 3.1, 1.5, 0.2]
4      [5.0, 3.6, 1.4, 0.2]
               ...         
145    [6.7, 3.0, 5.2, 2.3]
146    [6.3, 2.5, 5.0, 1.9]
147    [6.5, 3.0, 5.2, 2.0]
148    [6.2, 3.4, 5.4, 2.3]
149    [5.9, 3.0, 5.1, 1.8]
Name: x, Length: 150, dtype: object

In [61]:
neigh = KNeighborsClassifier(n_neighbors=len(np.unique(df['y'])))

In [62]:
neigh.fit(df['x'].tolist(), df['y'])

KNeighborsClassifier(n_neighbors=3)

In [63]:
neigh.predict([[5.2, 3.6, 1.39, 0.2]])

array([1])

In [64]:
from pyod.models.knn import KNN
from sklearn.model_selection import train_test_split

In [65]:
X_train, X_test, y_train, y_test = train_test_split(df[df.columns[:4]].values.tolist(), df['y'], test_size=0.33, shuffle=True, random_state=42)

In [66]:
clf = KNN()
clf.fit(X_train, y_train)

/home/grigo/.local/lib/python3.10/site-packages/pyod/models/base.py:430: UserWarning: y should not be presented in unsupervised learning.
  warnings.warn(


KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [67]:
y_train_pred = clf.labels_
clf.labels_

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [68]:
y_train_scores = clf.decision_scores_
clf.decision_scores_

array([0.3       , 0.80622577, 0.4472136 , 0.17320508, 0.96953597,
       0.38729833, 0.2236068 , 0.26457513, 0.5       , 0.82462113,
       0.43588989, 0.53851648, 0.42426407, 0.43588989, 0.31622777,
       0.17320508, 0.36055513, 1.13578167, 0.33166248, 0.42426407,
       0.58309519, 0.678233  , 0.43588989, 0.47958315, 0.59160798,
       0.51961524, 0.6244998 , 0.50990195, 0.47958315, 0.78740079,
       0.53851648, 0.2236068 , 0.33166248, 0.52915026, 0.54772256,
       0.3       , 0.72801099, 0.2236068 , 0.42426407, 0.54772256,
       0.9       , 0.37416574, 0.42426407, 0.73484692, 0.7       ,
       0.37416574, 0.43588989, 0.51961524, 0.678233  , 0.65574385,
       0.3       , 0.2       , 0.36055513, 0.46904158, 0.5       ,
       0.42426407, 0.42426407, 0.64807407, 0.3       , 0.43588989,
       0.46904158, 0.4472136 , 0.78740079, 0.52915026, 0.36055513,
       0.46904158, 0.38729833, 0.43588989, 0.68556546, 0.54772256,
       0.45825757, 0.83666003, 0.51961524, 0.47958315, 0.33166